spring:
  application:
    name: api-gateway
  config:
    import:
      - optional:file:common.env.properties
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
#  main:
#    web-application-type: reactive
#          routes:
#            - id: client_route
#              uri: lb://eureka-client
#              predicates:
#                - Path=/api/test
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8088/realms/market

server:
  port: 8080


app:
  jwt:
    secret: EFnoiYH3fUV5q9dls3vKojW0FBpZcueVC6UgQzLn68OaZKS5eDcnHdWLLLNEH3QQV76nRdnDg1kAjrKbWHrCoA==
    tokenExpiration: 10
    refreshTokenExpiration: 30

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL}

#eureka:
#  client:
#    enabled: false

logging:
  level:
    root: INFO
    ru.example.apigateway: DEBUG


