spring:
  application:
    name: user-service

  config:
    import:
      - optional:file:.env.properties
      - optional:file:../common.env.properties

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/app_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    hikari:
      maximum-pool-size: 5
      connection-timeout: 30000

  jpa:
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        order_inserts: true
        jdbc:
          batch_size: 1000

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8088/realms/market}

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: user-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        acks: all
        enable.idempotence: true

server:
  port: ${SERVER_PORT:0}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka}

market:
  kafka:
    topics:
      stock-reservation-requested: market.order.stock-reservation-requested.v1
      stock-reservation-result: market.product.stock-reservation-result.v1

  outbox:
    batch-size: 50
    max-attempts: 5
    publish-delay-ms: 5000
