spring:
  application:
    name: auth-module

  datasource:
    url: jdbc:postgresql://localhost:5432/app_db
    username: postgres
    password: postgres
    hikari:
      maximum-pool-size: 5
      connection-timeout: 30000
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        order_inserts: true
        jdbc:
          batch_size: 1000

#  mail:
#    host: smtp.yandex.ru
#    port: 465
#    username: ru.kirill.service@yandex.ru
#    password: dxfecwnvjopxnwuz
#    protocol: smtp
#    properties:
#      mail:
#        smtp:
#          auth: true
#          ssl:
#            enable: true
#            trust: smtp.yandex.ru


  mail:
    host: smtp.yandex.ru
    port: 465
    username: ru.kirill.service@yandex.ru
    password: dxfecwnvjopxnwuz
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
            trust: smtp.yandex.ru
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

#  mail:
#    host: smtp.yandex.ru
#    port: 465
#    username: ru.kirill.service@yandex.ru
#    password: pfnqjqfzybbooqgr
#    properties:
#      mail:
#        smtp:
#          auth: true
#          ssl:
#            enable: true
#    default-encoding: UTF-8

  data:
    redis:
      host: localhost
      port: 6379
      password: redis
      timeout: 2s
      lettuce:
        pool:
          max-active: 16
          max-idle: 8
          min-idle: 0

app:
  jwt:
    secret: EFnoiYH3fUV5q9dls3vKojW0FBpZcueVC6UgQzLn68OaZKS5eDcnHdWLLLNEH3QQV76nRdnDg1kAjrKbWHrCoA==
    tokenExpiration: 15m
  reset:
    url: http://127.0.0.1:9090/reset?token={token}
    redis:
      key-prefix: "pwdreset:tok:"
      ttl: 30m

  activation:
    url: http://127.0.0.1:9090/activation?token={token}
#    url: http://127.0.0.1:9090/api/v1/auth/activate?id={id}
    salt: KMvNn6W@fWdT3R3n
    redis:
      key-prefix: "acct:activate:tok:"
      ttl: 30m

  auth:
    refresh-ttl: 30d
    key:
      refresh-prefix: "auth:rt:"


server:
  port: 8181


#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8080/eureka
eureka:
  client:
    enabled: false

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
  api-docs:
    path: /v3/api-docs
